exec=killall panel 2>/dev/null || true && panel & disown
exec-once=~/.config/aether/autostart.sh
exec-once=run-wlsunset.sh init
exec-once=init-screen-scale
exec-once=init-lockscreen
exec-once=udiskie --automount --notify
exec-once=desktop
exec-once=nm-applet
exec-once=osd-notify
exec-once=AetherDock
exec-once=auth
exec-once=aetheridle before-sleep aetherlock
